name: CI Pipeline

on:
  push:
    branches: [ci-setup]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint || true

      - name: Run Codacy static analysis
        run: npx @codacy/codacy-analysis-cli analyze -t ${{ secrets.CODACY_PROJECT_TOKEN }}

