name: Generate JSDoc

on:
  push:
    branches: ['**']
    # Run only when real source files change—not for docs-only commits

jobs:
  generate-docs:
    permissions:
      contents: write
      pull-requests: write     # optional; used only if you add a PR comment
      actions: write           # lower-case; lets PAT trigger other workflows

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      - run: npm ci
      - run: npm run docs

      - name: Commit & push docs
        env: { GH_TOKEN: ${{ secrets.PAT }} }   # or drop this block and use GITHUB_TOKEN
        run: |
          git config --global user.name  "aFarahbakhsh1383"
          git config --global user.email "aFarahbakhsh1383@users.noreply.github.com"

          git add -f docs
          if git diff --cached --quiet; then
            echo "No JSDoc changes to commit"
          else
            git commit -m "Update JSDoc documentation"
            git push https://aFarahbakhsh1383:${GH_TOKEN}@github.com/${{ github.repository }} \
                     HEAD:${{ github.ref_name }}
          fi
