name: Generate JSDoc on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate JSDoc
        run: npm run docs

      - name: Commit and push updated docs
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          
          git add -f docs
          if git diff --cached --quiet; then
            echo "No JSDoc changes to commit"
          else
            git commit -m "Update JSDoc documentation"
            echo "Token User:"
            curl -s -H "Authorization: token ${GH_TOKEN}" https://api.github.com/user
            git push origin HEAD:${{ github.head_ref }}
          fi
